version: "3"

logs:
    mode: development
    channels:
        http:
            level: debug # Log all http requests, set to info to disable
        server:
            level: info # Everything written to worker stderr is logged
            mode: raw
        metrics:
            level: debug

service:
    messenger:
        command: "php bin/console messenger:consume async -vvvv"
        service_name_in_log: true
        processNum: 1
        execTimeout: 0
        remainAfterExit: false
        env:
            APP_ENV: "dev"
